export const esDataType: any = {
  // 文本类型
  text: "string",
  // 关键字类型
  keyword: "string",
  // 数字类型
  byte: "number",
  short: "number",
  integer: "number",
  long: "number",
  float: "number",
  double: "number",
  half_float: "number",
  scaled_float: "number",
  // 日期类型
  date: "string",
  // 布尔类型
  boolean: "boolean",
  // 二进制型,Base64编码字符串的二进制值
  binary: "string",
  // 范围类型
  integer_range: "any",
  long_range: "any",
  float_range: "any",
  double_range: "any",
  date_range: "any",
  ip_range: "any",
  // 地理点类型
  geo_point: "any",
  geo_shape: "any",
  // IP类型
  ip: "any",
  // 计数数据类型
  token_count: "any"
};
